before:
 - berks install --path ./cookbooks

environments:
  production:
    attributes:
      drupal-solr:
        solr_version: '1.4.0'
        app_name: 'reuters'
        home_dir: '/var/shared/sites/reuters/solr-home'
    run_list:
      - recipe[reuters-demo::default]
    nodes:
      server:
        before: apt-get update && apt-get install -q -y curl
        host: fqdn.for.your.remote.server
        user: root
      box:
        host: 192.168.50.4
        user: vagrant
        password: vagrant
        vagrant:
          IP: 192.168.50.4
          cpu: 1
          memory: 256
